Pin flake8 version before 3.7
Workaround tholo/pytest-flake8#56

```
AttributeError: 'Application' object has no attribute 'make_notifier'
```

introduced by https://gitlab.com/pycqa/flake8/merge_requests/274